### PR TITLE
Gesture Support

### PR DESCRIPTION
**Pull request by gili-labs**
Full support for gesture, including inspection of simple and composed gestures.

### CODE REVIEW

**Comment by nalexn** [comment]
This is incredible! Nicely done @gili-labs !

**Comment by gili-labs** [comment]
@nalexn I just realized I forgot to document the methods that support composed gestures. I will add this after you have merged this and submit a new PR for it. I would also like to add something on the coverage page.

**Comment by nalexn** [comment]
@gili-labs why don't you just update the original PR? I hope I'll get to review it and merge on the weekend. Keep me posted!

**Comment by gili-labs** [comment]
I didn't know you can do that. So, I guess the question I have is how to update a PR?

I'll try to update it as soon as possible. However, I lost my best engineer this week and have had to spend all my hours figuring out how my team is going to continue until I can replace him.

**Comment by nalexn** [comment]
Sorry to hear that... No rush, I'll get to review and merge on the weekend only, and can defer a bit longer if needed

**Comment by gili-labs** [comment]
Okay, I just read how to update a PR. I'll try to update it before the merge.

**Comment by gili-labs** [comment]
@nalexn I just committed changes to the guide documenting composed gestures and updates to the readiness list. Hence, this PR is ready for your review.

**Comment by nalexn** [comment]
`4289 insertions(+), 25 deletions(-)`

image

**Comment by nalexn** [comment]
@gili-labs may I ask you to revisit a couple of things:

1. Break up the `GestureTests.swift` in several logically scoped files. 3200 lines is too much. You can group them under a new folder
2. Install the `swiftlint` and fix all the syntax warnings it generates when you build the project. You need to run from under `ViewInspector.xcodeproj` to see them.

**Comment by gili-labs** [comment]
Okay, I'm on it...frightful looking image though.

**Comment by gili-labs** [comment]
@nalexn I've committed changes that bring the code into compliance with policies enforced by swiftlint.

**Comment by nalexn** [comment]
@gili-labs merged! Thank you for this **tremendous** work you've done!

I've also marked `@GestureState` modifier is "supported" in the readiness, considering you've used it in the tests, though do you know if there is anything else that can be added to better support it? Let me know!

**Comment by gili-labs** [comment]
@nalexn You're very welcome.

I only glossed over `@GestureState`, enough to support the inspection of gestures. It's a tough nut to crack, because under the covers it's tied into the gesture machinery. Love to take a crack at it more, and it's going to require me to look further into what you've done with other property wrappers.

The only other aspect of gestures I didn't do anything with is gesture's `map(_)` method. I couldn't find any real documentation, examples on the Internet, and when I tried to use it, it ended up using undocumented modifiers. Very strange stuff.

**Pull request merged**
