### PR TITLE
Add Podfile

### PR DESCRIPTION
**Pull request by YuantongL**
Support CocoaPods

### CODE REVIEW

**Comment by nalexn** [comment]
Hey @YuantongL 

Thank you for contributing. I was thinking if adding the support for CocoaPods and Carthage is actually needed.

My point is that the native tool (which is Swift Package Manager) is always preferable over any third-party solution, and given the fact that SPM is mature enough to be a stable and flexible dependency manager, CocoaPods and Carthage can be considered obsolete.

SwiftUI is a huge step forward in the iOS development, literally a revolution, and I'm not convinced we need to drag the past to the bright future.

I understand that having to mix multiple dependency managers in one project is inconvenient, but a better way would be to convince others to support SPM rather than stay with legacy solutions.

Let me know your thoughts, maybe I'm missing something.

**Comment by YuantongL** [comment]
Hi @nalexn, thanks for writing this library, I really like to make use of this, our codebase uses CocoaPods only, I wouldn't consider CocoaPods legacy, CocoaPods is just another way of doing it and I'm sure there are more projects based on CocoaPods.

Also this is a single file change that can bridge your library to more audience, which I think is worth it. But it's up to you.

**Comment by nalexn** [comment]
Hey @YuantongL 

Could you add my email (alexey ~at~ naumov.tech) on cocoapods for the ViewInspector. I can see the version on CocoaPods is very old, wanted to push an updated one.

**Comment by YuantongL** [comment]
> Hey @YuantongL
> 
> Could you add my email (alexey >~at~< naumov.tech) on cocoapods for the ViewInspector. I can see the version on CocoaPods is very old, wanted to push an updated one.

OK, I no longer have access to my registered email, I'm filing a claim to Cocoapod. Will update you as soon as I heard back from them.

**Comment by nalexn** [comment]
@YuantongL did you hear back from the Cocoapods team?

**Comment by YuantongL** [comment]
> @YuantongL did you hear back from the Cocoapods team?

Not yet, I'm filing another claim now.

**Comment by amorde** [comment]
Just settled this one now - thanks for your patience.

@nalexn you are now the sole owner of this Pod

**Pull request merged**
